@startuml

participant "Key1 :HTMLElement" as Key1
participant ":ZahlEingeben" as ZahlEingeben
participant ":CalculatorContext" as CalculatorContext
participant "Display :HTMLElement" as Display

Key1 -> ZahlEingeben: key1Pressed()
ZahlEingeben -> CalculatorContext: get displayValue()
ZahlEingeben -> CalculatorContext: set displayValue()
CalculatorContext -> Display: set innerText()

@enduml