@startuml

actor client
participant calculatorContext
participant GuiAdapter
participant displayValue

client -> calculatorContext : setDisplayValue()
calculatorContext -> GuiAdapter : displayValue()
calculatorContext -> displayValue : innerText()



@enduml