@startuml

actor client
participant calculatorContext
participant GuiAdapter

client -> calculatorContext : setDisplayValue()
calculatorContext -> GuiAdapter : setDisplayValue() : displayValue
GuiAdapter -> GuiAdapter : HTMLElement : HTML.innerText()



@enduml